---
title: Tidy Tuesday 2020-02 - Australia Fires
author: James Wade
date: '2020-01-07'
slug: tidy-tuesday-2020-02-australia-fires
categories:
  - R
  - climate change
  - natural disaster
tags:
  - data viz
  - plot
  - R Markdown
  - TidyTuesday
runtime: shiny
---



The 2nd (1st?) [#TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-07/readme.md) of the year is on the Australia Bush Fires that are currently (as of 2020-01-07) raging. To display the temperature data, I built a shiny app.

<iframe src="https://james-h-wade.shinyapps.io/TidyTuesday_2019-02/" width=1000 height=800"></iframe>

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::include_app("https://james-h-wade.shinyapps.io/TidyTuesday_2019-02/", height = "100%")



```


```{r include=FALSE, eval=FALSE}
ggplot(sample_n(temperature_2, 1e4), 
       aes(x = year, y = score, color = score)) + 
  geom_point(alpha = 0.4) +
  scale_color_viridis_c(option = "B") + facet_wrap(~city_name, scales = "free") +
  geom_smooth()

library(gganimate)

small_temp <- sample_n(temperature_2, 1e5) %>% filter(year > 1950)

ggplot(small_temp) + 
  geom_density(aes(x = temperature, fill = city_name), alpha = 0.5) +
  transition_reveal(year)

years <- sample(unique(temperature_2$year), 2)

a <- temperature_2 %>% filter(year %in% years)

avg <- a %>% select(city_name, temp_type, site_name, month, day, avg_temp) %>% distinct()

ggplot(a) + 
  geom_density(data = avg, aes(x = avg_temp), fill = "grey") +  
  geom_density(aes(x = temperature, fill = factor(year)), alpha = 0.5) +
  facet_wrap(~city_name) +
  cowplot::theme_cowplot()


b <- temperature_2 %>% filter(city_name == "SYDNEY") %>% 
  mutate(year = as.integer(year)) %>% 
  group_by(year) %>% mutate(mean_temp = mean(temperature))

avg <- b %>% select(city_name, temp_type, site_name, month, day, avg_temp) %>% distinct() %>% 
  mutate(year = as.integer(year))

ggplot(b) + 
  # geom_density(data = avg, aes(x = avg_temp), fill = "grey") +  
  geom_density(aes(x = temperature, fill = mean_temp), alpha = 0.5) +
  scale_fill_viridis_c(option = "C") +
  geom_vline(aes(xintercept = mean_temp), linetype = "dashed") +
  cowplot::theme_cowplot() + theme(legend.position = "none") +
  theme(axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank()) +
  transition_time(year) + ease_aes("linear") +
  labs(x = "Temperature", subtitle = "Temperature Distribution by Year in Sidney", title = "Year: {frame_time}",
       caption = "#TidyTuesday | @JamesHWade")
```

