---
title: Tidy Tuesday 2020-02 - Australia Fires
author: James Wade
date: '2020-01-07'
slug: tidy-tuesday-2020-02-australia-fires
categories:
  - R
  - climate change
  - natural disaster
tags:
  - data viz
  - plot
  - R Markdown
  - TidyTuesday
---

The 2nd (1st?) [#TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-07/readme.md) of the year is on the Australia Bush Fires that are currently (as of 2020-01-07) raging.

## Data Import

```{r message=FALSE, warning=FALSE}
library(tidyverse)

# note: as of writing this, the tidytuesdayR package was not working for this set
# importing the old fashion way...
rainfall <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/rainfall.csv')
temperature <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv')

url <- "http://www.rfs.nsw.gov.au/feeds/majorIncidents.json"

aus_fires <- sf::st_read(url)
```

```{r}
library(ggthemes)
library(ggtext)
library(geofacet)
library(sf)
library(rnaturalearth)
library(noncensus)

ggplot(aus_fires) + geom_sf()

temperature_2 <- temperature %>% 
  filter(complete.cases(.) & temp_type == "max") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date)) %>% 
  group_by(month, day, city_name, temp_type) %>% 
  mutate(avg_temp = mean(temperature),
         std_dev = sd(temperature),
         score = (temperature - avg_temp) / std_dev) %>% 
  ungroup()

ggplot(sample_n(temperature_2, 1e4), 
       aes(x = year, y = score, color = score)) + 
  geom_point(alpha = 0.4) +
  scale_color_viridis_c(option = "B") + facet_wrap(~city_name, scales = "free") +
  geom_smooth()

library(gganimate)

small_temp <- sample_n(temperature_2, 1e5) %>% filter(year > 1950)

ggplot(small_temp) + 
  geom_density(aes(x = temperature, fill = city_name), alpha = 0.5) +
  transition_reveal(year)

years <- sample(unique(temperature_2$year), 2)

a <- temperature_2 %>% filter(year %in% years)

avg <- a %>% select(city_name, temp_type, site_name, month, day, avg_temp) %>% distinct()

ggplot(a) + 
  geom_density(data = avg, aes(x = avg_temp), fill = "grey") +  
  geom_density(aes(x = temperature, fill = factor(year)), alpha = 0.5) +
    facet_wrap(~city_name) +
  cowplot::theme_cowplot()

# aus <- ne_states(country = "Australia", returnclass = 'sf')

# ggplot(aus) + geom_sf() + 
#   geom_point(data = sample_n(rainfall_2, 1e4), aes(y = lat, x = long, color = ), alpha = 0.4)
```

