---
title: A Collection of Resources for Learning R
author: James Wade
date: '2020-02-26'
slug: a-collection-of-resources-for-learning-r
categories:
  - R
  - list
  - curation
  - learning
tags:
  - learning
---

## Introduction to the Tidyverse

### Books

- [R for Data Science](https://r4ds.had.co.nz/)
- [R Cookbook](https://rc2e.com/)

### Workshops from RStudio

- [R for Excel Users](https://github.com/rstudio-conf-2020/r-for-excel/)
- [Introduction to Data Science in the Tidyverse](https://github.com/rstudio-conf-2020/data-science-tidy#introduction-to-data-science-in-the-tidyverse)
- [Data Visualization with ggplot2](https://github.com/rstudio-conf-2020/dataviz)
- [Primers from RStudio](https://rstudio.cloud/learn/primers)

### Seminars/Lectures

- [Intro to the Tidyverse by Thomas Mock](https://www.youtube.com/watch?v=MKwyauo8nSI)
- [Tidyverse Primer from RStudio](https://www.youtube.com/playlist?list=PL9HYL-VRX0oQOWAFoKHFQAsWAI3ImbNPk)

### Courses

- [Intro to Tidyverse - LinkedIn Learning](https://www.linkedin.com/learning/learning-the-r-tidyverse/welcome)
- [R Statistics - LinkedIn Learning](https://www.linkedin.com/learning/r-statistics-essential-training)
- [Data Science Specialization from Johns Hopkins - Coursera](https://www.coursera.org/specializations/jhu-data-science#courses)
- [Data Science Series from Harvard - edX](https://www.edx.org/professional-certificate/harvardx-data-science)

## Intermediate/Advanced R Users

### Books

- [R Graphics Cookbook](https://r-graphics.org/)
- [R Markdown](https://bookdown.org/yihui/rmarkdown/)
- [Advanced R](https://adv-r.hadley.nz/)
- [R Packages](https://r-pkgs.org/)
- [Hands on Machine Learning with R](https://bradleyboehmke.github.io/HOML/index.html#)

### Workshops from RStudio

- [What They Forgot to Teach You about R](https://github.com/rstudio-conf-2020/what-they-forgot)
- [Tidy Time Series Analysis and Forecasting](https://github.com/rstudio-conf-2020/time-series-forecasting)
- [Big Data with dplyr](https://github.com/rstudio-conf-2020/big-data)
- [Applied Machine Learning](https://github.com/rstudio-conf-2020/applied-ml)

### Seminars/Lectures

- [Talks from rstudio::conf2020](https://resources.rstudio.com/rstudio-conf-2020)

### Recommended Data Science Talks

- [Letters to a Young Maintainer](https://youtu.be/1K7u5hkciLI) by Hadley Wickham
- [Topological Techniques for Unsupervised Learning](https://youtu.be/7pAVPjwBppo) by Leland Mcinnes at PyData LA 2019
- [Visualizing uncertainty with hypothetical outcomes plots](https://youtu.be/SjYwhku2si0) by Claus Wilke at rstudio::conf 2019
- [Teaching R to New Users: From tapply to Tidyverse](https://youtu.be/5033jBHFiHE) by Roger Peng at UseR 2018